// Generated by scripts/build-catalog.py. Names are editorial translations, pending specialist review.
window.ANATOMY_CATALOG = {
  "parietalboner001": {
    "name": "Osso parietal",
    "original": "Parietal bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "parietalbonel001": {
    "name": "Osso parietal",
    "original": "Parietal bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "sinusoffrontalbone001": {
    "name": "Seio frontal",
    "original": "Sinus of frontal bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "frontalbone001": {
    "name": "Osso frontal",
    "original": "Frontal bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "occipitalbone001": {
    "name": "Osso occipital",
    "original": "Occipital bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "sinusofsphenoidbone001": {
    "name": "Seio esfenoidal",
    "original": "Sinus of sphenoid bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "sphenoidbone001": {
    "name": "Osso esfenoide",
    "original": "Sphenoid bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "temporalboner001": {
    "name": "Osso temporal",
    "original": "Temporal bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "ethmoidbone001": {
    "name": "Osso etmoide",
    "original": "Ethmoid bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "inferiornasalconchaboner001": {
    "name": "Concha nasal inferior",
    "original": "Inferior nasal concha bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "lacrimalboner001": {
    "name": "Osso lacrimal",
    "original": "Lacrimal bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "nasalboner001": {
    "name": "Osso nasal",
    "original": "Nasal bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "maxillar001": {
    "name": "Maxila",
    "original": "Maxilla",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "palatineboner001": {
    "name": "Osso palatino",
    "original": "Palatine bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "zygomaticboner001": {
    "name": "Osso zigomático",
    "original": "Zygomatic bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "mandible001": {
    "name": "Mandíbula",
    "original": "Mandible",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "hyoidbone001": {
    "name": "Osso hioide",
    "original": "Hyoid bone",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "malleusr001": {
    "name": "Martelo",
    "original": "Malleus",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "incusr001": {
    "name": "Bigorna",
    "original": "Incus",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "stapesr001": {
    "name": "Estribo",
    "original": "Stapes",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "uppermedialincisorr001": {
    "name": "Incisivo central superior",
    "original": "Upper medial incisor",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "upperlateralincisorr001": {
    "name": "Incisivo lateral superior",
    "original": "Upper lateral incisor",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "uppercaniner001": {
    "name": "Canino superior",
    "original": "Upper canine",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowermedialincisorr001": {
    "name": "Incisivo central inferior",
    "original": "Lower medial incisor",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowerlateralincisorr001": {
    "name": "Incisivo lateral inferior",
    "original": "Lower lateral incisor",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowercaniner001": {
    "name": "Canino inferior",
    "original": "Lower canine",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "upperfirstpremolarr001": {
    "name": "1º pré-molar superior",
    "original": "Upper first premolar",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "uppersecondpremolarr001": {
    "name": "2º pré-molar superior",
    "original": "Upper second premolar",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "upperfirstmolartoothr001": {
    "name": "1º molar superior",
    "original": "Upper first molar tooth",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "uppersecondmolartoothr001": {
    "name": "2º molar superior",
    "original": "Upper second molar tooth",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowerfirstpremolarr001": {
    "name": "1º pré-molar inferior",
    "original": "Lower first premolar",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowersecondpremolarr001": {
    "name": "2º pré-molar inferior",
    "original": "Lower second premolar",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowerfirstmolartoothr001": {
    "name": "1º molar inferior",
    "original": "Lower first molar tooth",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowersecondmolartoothr001": {
    "name": "2º molar inferior",
    "original": "Lower second molar tooth",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "majoralarcartilager001": {
    "name": "Cartilagem alar maior",
    "original": "Major alar cartilage",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "lateralprocessofnasalseptalcartilager001": {
    "name": "Processo lateral da cartilagem do septo nasal",
    "original": "Lateral process of nasal septal cartilage",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "nasalseptalcartilage001": {
    "name": "Cartilagem do septo nasal",
    "original": "Nasal septal cartilage",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "thyroidcartilage001": {
    "name": "Cartilagem tireóidea",
    "original": "Thyroid cartilage",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "cricoidcartilage001": {
    "name": "Cartilagem cricóidea",
    "original": "Cricoid cartilage",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "arytenoidcartilager001": {
    "name": "Cartilagem aritenóidea",
    "original": "Arytenoid cartilage",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "corniculatecartilager001": {
    "name": "Cartilagem corniculada",
    "original": "Corniculate cartilage",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "atlasc1001": {
    "name": "Atlas (C1)",
    "original": "Atlas (C1)",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrac6001": {
    "name": "Vértebra C6",
    "original": "Vertebra C6",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrac3001": {
    "name": "Vértebra C3",
    "original": "Vertebra C3",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrac5001": {
    "name": "Vértebra C5",
    "original": "Vertebra C5",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrac7001": {
    "name": "Vértebra C7",
    "original": "Vertebra C7",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrac4001": {
    "name": "Vértebra C4",
    "original": "Vertebra C4",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat2001": {
    "name": "Vértebra T2",
    "original": "Vertebra T2",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat3001": {
    "name": "Vértebra T3",
    "original": "Vertebra T3",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat4001": {
    "name": "Vértebra T4",
    "original": "Vertebra T4",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat5001": {
    "name": "Vértebra T5",
    "original": "Vertebra T5",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat6001": {
    "name": "Vértebra T6",
    "original": "Vertebra T6",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat7001": {
    "name": "Vértebra T7",
    "original": "Vertebra T7",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat9001": {
    "name": "Vértebra T9",
    "original": "Vertebra T9",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat10001": {
    "name": "Vértebra T10",
    "original": "Vertebra T10",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat11001": {
    "name": "Vértebra T11",
    "original": "Vertebra T11",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat12001": {
    "name": "Vértebra T12",
    "original": "Vertebra T12",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat8001": {
    "name": "Vértebra T8",
    "original": "Vertebra T8",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebrat1001": {
    "name": "Vértebra T1",
    "original": "Vertebra T1",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebral1001": {
    "name": "Vértebra L1",
    "original": "Vertebra L1",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebral2001": {
    "name": "Vértebra L2",
    "original": "Vertebra L2",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebral4001": {
    "name": "Vértebra L4",
    "original": "Vertebra L4",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebral5001": {
    "name": "Vértebra L5",
    "original": "Vertebra L5",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "vertebral3001": {
    "name": "Vértebra L3",
    "original": "Vertebra L3",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "coccyx001": {
    "name": "Cóccix",
    "original": "Coccyx",
    "side": "midline",
    "region": "Pelve",
    "kind": "Estrutura óssea"
  },
  "fifthribr001": {
    "name": "5ª costela",
    "original": "Fifth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "firstribr001": {
    "name": "1ª costela",
    "original": "First rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "fourthribr001": {
    "name": "4ª costela",
    "original": "Fourth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "secondribr001": {
    "name": "2ª costela",
    "original": "Second rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "seventhribr001": {
    "name": "7ª costela",
    "original": "Seventh rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "sixthribr001": {
    "name": "6ª costela",
    "original": "Sixth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "thirdribr001": {
    "name": "3ª costela",
    "original": "Third rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "eleventhribr001": {
    "name": "11ª costela",
    "original": "Eleventh rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "twelfthribr001": {
    "name": "12ª costela",
    "original": "Twelfth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "eighthribr001": {
    "name": "8ª costela",
    "original": "Eighth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "ninthribr001": {
    "name": "9ª costela",
    "original": "Ninth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "tenthribr001": {
    "name": "10ª costela",
    "original": "Tenth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "manubriumofsternum001": {
    "name": "Manúbrio do esterno",
    "original": "Manubrium of sternum",
    "side": "midline",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "xiphoidprocess001": {
    "name": "Processo xifoide",
    "original": "Xiphoid process",
    "side": "midline",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "bodyofsternum001": {
    "name": "Corpo do esterno",
    "original": "Body of sternum",
    "side": "midline",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "costalcartilageoffirstribr001": {
    "name": "Cartilagem costal da 1ª costela",
    "original": "Costal cartilage of first rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofsecondribr001": {
    "name": "Cartilagem costal da 2ª costela",
    "original": "Costal cartilage of second rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofthirdribr001": {
    "name": "Cartilagem costal da 3ª costela",
    "original": "Costal cartilage of third rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageoffourthribr001": {
    "name": "Cartilagem costal da 4ª costela",
    "original": "Costal cartilage of fourth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageoffifthribr001": {
    "name": "Cartilagem costal da 5ª costela",
    "original": "Costal cartilage of fifth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofsixthribr001": {
    "name": "Cartilagem costal da 6ª costela",
    "original": "Costal cartilage of sixth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofseventhribr001": {
    "name": "Cartilagem costal da 7ª costela",
    "original": "Costal cartilage of seventh rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofeighthribr001": {
    "name": "Cartilagem costal da 8ª costela",
    "original": "Costal cartilage of eighth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageoftenthribr001": {
    "name": "Cartilagem costal da 10ª costela",
    "original": "Costal cartilage of tenth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofninthribr001": {
    "name": "Cartilagem costal da 9ª costela",
    "original": "Costal cartilage of ninth rib",
    "side": "right",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "clavicler001": {
    "name": "Clavícula",
    "original": "Clavicle",
    "side": "right",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "humerusr001": {
    "name": "Úmero",
    "original": "Humerus",
    "side": "right",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "patellar001": {
    "name": "Patela",
    "original": "Patella",
    "side": "right",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "talusr001": {
    "name": "Tálus",
    "original": "Talus",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "calcaneusr001": {
    "name": "Calcâneo",
    "original": "Calcaneus",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "navicularboner001": {
    "name": "Osso navicular",
    "original": "Navicular bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "cuboidboner001": {
    "name": "Osso cuboide",
    "original": "Cuboid bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "intermediatecuneiformboner001": {
    "name": "Osso cuneiforme intermédio",
    "original": "Intermediate cuneiform bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "lateralcuneiformboner001": {
    "name": "Osso cuneiforme lateral",
    "original": "Lateral cuneiform bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "medialcuneiformboner001": {
    "name": "Osso cuneiforme medial",
    "original": "Medial cuneiform bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "firstmetatarsalboner001": {
    "name": "1º metatarsal",
    "original": "First metatarsal bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "fifthmetatarsalboner001": {
    "name": "5º metatarsal",
    "original": "Fifth metatarsal bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "secondmetatarsalboner001": {
    "name": "2º metatarsal",
    "original": "Second metatarsal bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "thirdmetatarsalboner001": {
    "name": "3º metatarsal",
    "original": "Third metatarsal bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "fourthmetatarsalboner001": {
    "name": "4º metatarsal",
    "original": "Fourth metatarsal bone",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffifthfingeroffootr001": {
    "name": "Falange distal do 5º dedo do pé",
    "original": "Distal phalanx of fifth finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffirstfingeroffootr001": {
    "name": "Falange distal do 1º dedo do pé",
    "original": "Distal phalanx of first finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffourthfingeroffootr001": {
    "name": "Falange distal do 4º dedo do pé",
    "original": "Distal phalanx of fourth finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofsecondfingeroffootr001": {
    "name": "Falange distal do 2º dedo do pé",
    "original": "Distal phalanx of second finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofthirdfingeroffootr001": {
    "name": "Falange distal do 3º dedo do pé",
    "original": "Distal phalanx of third finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofsecondfingeroffootr001": {
    "name": "Falange média do 2º dedo do pé",
    "original": "Middle phalanx of second finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofthirdfingeroffootr001": {
    "name": "Falange média do 3º dedo do pé",
    "original": "Middle phalanx of third finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffourthfingeroffootr001": {
    "name": "Falange média do 4º dedo do pé",
    "original": "Middle phalanx of fourth finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffifthfingeroffootr001": {
    "name": "Falange média do 5º dedo do pé",
    "original": "Middle phalanx of fifth finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffirstfingeroffootr001": {
    "name": "Falange proximal do 1º dedo do pé",
    "original": "Proximal phalanx of first finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofsecondfingeroffootr001": {
    "name": "Falange proximal do 2º dedo do pé",
    "original": "Proximal phalanx of second finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofthirdfingeroffootr001": {
    "name": "Falange proximal do 3º dedo do pé",
    "original": "Proximal phalanx of third finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffourthfingeroffootr001": {
    "name": "Falange proximal do 4º dedo do pé",
    "original": "Proximal phalanx of fourth finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffifthfingeroffootr001": {
    "name": "Falange proximal do 5º dedo do pé",
    "original": "Proximal phalanx of fifth finger of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "sesamoidbonesoffootr001": {
    "name": "Ossos sesamoides do pé",
    "original": "Sesamoid bones of foot",
    "side": "right",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffirstfingerofhandr001": {
    "name": "Falange distal do 1º dedo da mão",
    "original": "Distal phalanx of first finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofsecondfingerofhandr001": {
    "name": "Falange distal do 2º dedo da mão",
    "original": "Distal phalanx of second finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofthirdfingerofhandr001": {
    "name": "Falange distal do 3º dedo da mão",
    "original": "Distal phalanx of third finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffourthfingerofhandr001": {
    "name": "Falange distal do 4º dedo da mão",
    "original": "Distal phalanx of fourth finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffifthfingerofhandr001": {
    "name": "Falange distal do 5º dedo da mão",
    "original": "Distal phalanx of fifth finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofsecondfingerofhandr001": {
    "name": "Falange média do 2º dedo da mão",
    "original": "Middle phalanx of second finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofthirdfingerofhandr001": {
    "name": "Falange média do 3º dedo da mão",
    "original": "Middle phalanx of third finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffourthfingerofhandr001": {
    "name": "Falange média do 4º dedo da mão",
    "original": "Middle phalanx of fourth finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffifthfingerofhandr001": {
    "name": "Falange média do 5º dedo da mão",
    "original": "Middle phalanx of fifth finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffirstfingerofhandr001": {
    "name": "Falange proximal do 1º dedo da mão",
    "original": "Proximal phalanx of first finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofsecondfingerofhandr001": {
    "name": "Falange proximal do 2º dedo da mão",
    "original": "Proximal phalanx of second finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofthirdfingerofhandr001": {
    "name": "Falange proximal do 3º dedo da mão",
    "original": "Proximal phalanx of third finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffourthfingerofhandr001": {
    "name": "Falange proximal do 4º dedo da mão",
    "original": "Proximal phalanx of fourth finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffifthfingerofhandr001": {
    "name": "Falange proximal do 5º dedo da mão",
    "original": "Proximal phalanx of fifth finger of hand",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "firstmetacarpalboner001": {
    "name": "1º metacarpal",
    "original": "First metacarpal bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "secondmetacarpalboner001": {
    "name": "2º metacarpal",
    "original": "Second metacarpal bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "thirdmetacarpalboner001": {
    "name": "3º metacarpal",
    "original": "Third metacarpal bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "fourthmetacarpalboner001": {
    "name": "4º metacarpal",
    "original": "Fourth metacarpal bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "fifthmetacarpalboner001": {
    "name": "5º metacarpal",
    "original": "Fifth metacarpal bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "capitateboner001": {
    "name": "Osso capitato",
    "original": "Capitate bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "hamateboner001": {
    "name": "Osso hamato",
    "original": "Hamate bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "lunateboner001": {
    "name": "Osso semilunar",
    "original": "Lunate bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "pisiformboner001": {
    "name": "Osso pisiforme",
    "original": "Pisiform bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "scaphoidboner001": {
    "name": "Osso escafoide",
    "original": "Scaphoid bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "trapeziumboner001": {
    "name": "Osso trapézio",
    "original": "Trapezium bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "trapezoidboner001": {
    "name": "Osso trapezoide",
    "original": "Trapezoid bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "triquetrumboner001": {
    "name": "Osso piramidal",
    "original": "Triquetrum bone",
    "side": "right",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "axisc2001": {
    "name": "Áxis (C2)",
    "original": "Axis (C2)",
    "side": "midline",
    "region": "Coluna vertebral",
    "kind": "Estrutura óssea"
  },
  "scapular001": {
    "name": "Escápula",
    "original": "Scapula",
    "side": "right",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "radiusr001": {
    "name": "Rádio",
    "original": "Radius",
    "side": "right",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "ulnar001": {
    "name": "Ulna",
    "original": "Ulna",
    "side": "right",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "femurr001": {
    "name": "Fêmur",
    "original": "Femur",
    "side": "right",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "hipboner001": {
    "name": "Osso do quadril",
    "original": "Hip bone",
    "side": "right",
    "region": "Pelve",
    "kind": "Estrutura óssea"
  },
  "tibiar001": {
    "name": "Tíbia",
    "original": "Tibia",
    "side": "right",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "fibular001": {
    "name": "Fíbula",
    "original": "Fibula",
    "side": "right",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "sacrum001": {
    "name": "Sacro",
    "original": "Sacrum",
    "side": "midline",
    "region": "Pelve",
    "kind": "Estrutura óssea"
  },
  "temporalbonel001": {
    "name": "Osso temporal",
    "original": "Temporal bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "inferiornasalconchabonel001": {
    "name": "Concha nasal inferior",
    "original": "Inferior nasal concha bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "lacrimalbonel001": {
    "name": "Osso lacrimal",
    "original": "Lacrimal bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "nasalbonel001": {
    "name": "Osso nasal",
    "original": "Nasal bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "vomer001": {
    "name": "Vômer",
    "original": "Vomer",
    "side": "midline",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "maxillal001": {
    "name": "Maxila",
    "original": "Maxilla",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "palatinebonel001": {
    "name": "Osso palatino",
    "original": "Palatine bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "zygomaticbonel001": {
    "name": "Osso zigomático",
    "original": "Zygomatic bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "malleusl001": {
    "name": "Martelo",
    "original": "Malleus",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "incusl001": {
    "name": "Bigorna",
    "original": "Incus",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "stapesl001": {
    "name": "Estribo",
    "original": "Stapes",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Estrutura óssea"
  },
  "uppermedialincisorl001": {
    "name": "Incisivo central superior",
    "original": "Upper medial incisor",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "upperlateralincisorl001": {
    "name": "Incisivo lateral superior",
    "original": "Upper lateral incisor",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "uppercaninel001": {
    "name": "Canino superior",
    "original": "Upper canine",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowermedialincisorl001": {
    "name": "Incisivo central inferior",
    "original": "Lower medial incisor",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowerlateralincisorl001": {
    "name": "Incisivo lateral inferior",
    "original": "Lower lateral incisor",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowercaninel001": {
    "name": "Canino inferior",
    "original": "Lower canine",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "upperfirstpremolarl001": {
    "name": "1º pré-molar superior",
    "original": "Upper first premolar",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "uppersecondpremolarl001": {
    "name": "2º pré-molar superior",
    "original": "Upper second premolar",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "upperfirstmolartoothl001": {
    "name": "1º molar superior",
    "original": "Upper first molar tooth",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "uppersecondmolartoothl001": {
    "name": "2º molar superior",
    "original": "Upper second molar tooth",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowerfirstpremolarl001": {
    "name": "1º pré-molar inferior",
    "original": "Lower first premolar",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowersecondpremolarl001": {
    "name": "2º pré-molar inferior",
    "original": "Lower second premolar",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowerfirstmolartoothl001": {
    "name": "1º molar inferior",
    "original": "Lower first molar tooth",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "lowersecondmolartoothl001": {
    "name": "2º molar inferior",
    "original": "Lower second molar tooth",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Dente"
  },
  "majoralarcartilagel001": {
    "name": "Cartilagem alar maior",
    "original": "Major alar cartilage",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "lateralprocessofnasalseptalcartilagel001": {
    "name": "Processo lateral da cartilagem do septo nasal",
    "original": "Lateral process of nasal septal cartilage",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "arytenoidcartilagel001": {
    "name": "Cartilagem aritenóidea",
    "original": "Arytenoid cartilage",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "corniculatecartilagel001": {
    "name": "Cartilagem corniculada",
    "original": "Corniculate cartilage",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cartilagem"
  },
  "fifthribl001": {
    "name": "5ª costela",
    "original": "Fifth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "firstribl001": {
    "name": "1ª costela",
    "original": "First rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "fourthribl001": {
    "name": "4ª costela",
    "original": "Fourth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "secondribl001": {
    "name": "2ª costela",
    "original": "Second rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "seventhribl001": {
    "name": "7ª costela",
    "original": "Seventh rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "sixthribl001": {
    "name": "6ª costela",
    "original": "Sixth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "thirdribl001": {
    "name": "3ª costela",
    "original": "Third rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "eleventhribl001": {
    "name": "11ª costela",
    "original": "Eleventh rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "twelfthribl001": {
    "name": "12ª costela",
    "original": "Twelfth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "ninthribl001": {
    "name": "9ª costela",
    "original": "Ninth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "tenthribl001": {
    "name": "10ª costela",
    "original": "Tenth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  },
  "costalcartilageoffirstribl001": {
    "name": "Cartilagem costal da 1ª costela",
    "original": "Costal cartilage of first rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofsecondribl001": {
    "name": "Cartilagem costal da 2ª costela",
    "original": "Costal cartilage of second rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofthirdribl001": {
    "name": "Cartilagem costal da 3ª costela",
    "original": "Costal cartilage of third rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageoffourthribl001": {
    "name": "Cartilagem costal da 4ª costela",
    "original": "Costal cartilage of fourth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageoffifthribl001": {
    "name": "Cartilagem costal da 5ª costela",
    "original": "Costal cartilage of fifth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofsixthribl001": {
    "name": "Cartilagem costal da 6ª costela",
    "original": "Costal cartilage of sixth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofseventhribl001": {
    "name": "Cartilagem costal da 7ª costela",
    "original": "Costal cartilage of seventh rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofeighthribl001": {
    "name": "Cartilagem costal da 8ª costela",
    "original": "Costal cartilage of eighth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageoftenthribl001": {
    "name": "Cartilagem costal da 10ª costela",
    "original": "Costal cartilage of tenth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "costalcartilageofninthribl001": {
    "name": "Cartilagem costal da 9ª costela",
    "original": "Costal cartilage of ninth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Cartilagem"
  },
  "claviclel001": {
    "name": "Clavícula",
    "original": "Clavicle",
    "side": "left",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "humerusl001": {
    "name": "Úmero",
    "original": "Humerus",
    "side": "left",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "patellal001": {
    "name": "Patela",
    "original": "Patella",
    "side": "left",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "talusl001": {
    "name": "Tálus",
    "original": "Talus",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "calcaneusl001": {
    "name": "Calcâneo",
    "original": "Calcaneus",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "navicularbonel001": {
    "name": "Osso navicular",
    "original": "Navicular bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "cuboidbonel001": {
    "name": "Osso cuboide",
    "original": "Cuboid bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "intermediatecuneiformbonel001": {
    "name": "Osso cuneiforme intermédio",
    "original": "Intermediate cuneiform bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "lateralcuneiformbonel001": {
    "name": "Osso cuneiforme lateral",
    "original": "Lateral cuneiform bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "medialcuneiformbonel001": {
    "name": "Osso cuneiforme medial",
    "original": "Medial cuneiform bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "firstmetatarsalbonel001": {
    "name": "1º metatarsal",
    "original": "First metatarsal bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "fifthmetatarsalbonel001": {
    "name": "5º metatarsal",
    "original": "Fifth metatarsal bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "secondmetatarsalbonel001": {
    "name": "2º metatarsal",
    "original": "Second metatarsal bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "thirdmetatarsalbonel001": {
    "name": "3º metatarsal",
    "original": "Third metatarsal bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "fourthmetatarsalbonel001": {
    "name": "4º metatarsal",
    "original": "Fourth metatarsal bone",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffifthfingeroffootl001": {
    "name": "Falange distal do 5º dedo do pé",
    "original": "Distal phalanx of fifth finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffirstfingeroffootl001": {
    "name": "Falange distal do 1º dedo do pé",
    "original": "Distal phalanx of first finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffourthfingeroffootl001": {
    "name": "Falange distal do 4º dedo do pé",
    "original": "Distal phalanx of fourth finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofsecondfingeroffootl001": {
    "name": "Falange distal do 2º dedo do pé",
    "original": "Distal phalanx of second finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofthirdfingeroffootl001": {
    "name": "Falange distal do 3º dedo do pé",
    "original": "Distal phalanx of third finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofsecondfingeroffootl001": {
    "name": "Falange média do 2º dedo do pé",
    "original": "Middle phalanx of second finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofthirdfingeroffootl001": {
    "name": "Falange média do 3º dedo do pé",
    "original": "Middle phalanx of third finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffourthfingeroffootl001": {
    "name": "Falange média do 4º dedo do pé",
    "original": "Middle phalanx of fourth finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffifthfingeroffootl001": {
    "name": "Falange média do 5º dedo do pé",
    "original": "Middle phalanx of fifth finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffirstfingeroffootl001": {
    "name": "Falange proximal do 1º dedo do pé",
    "original": "Proximal phalanx of first finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofsecondfingeroffootl001": {
    "name": "Falange proximal do 2º dedo do pé",
    "original": "Proximal phalanx of second finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofthirdfingeroffootl001": {
    "name": "Falange proximal do 3º dedo do pé",
    "original": "Proximal phalanx of third finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffourthfingeroffootl001": {
    "name": "Falange proximal do 4º dedo do pé",
    "original": "Proximal phalanx of fourth finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffifthfingeroffootl001": {
    "name": "Falange proximal do 5º dedo do pé",
    "original": "Proximal phalanx of fifth finger of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "sesamoidbonesoffootl001": {
    "name": "Ossos sesamoides do pé",
    "original": "Sesamoid bones of foot",
    "side": "left",
    "region": "Pés",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffirstfingerofhandl001": {
    "name": "Falange distal do 1º dedo da mão",
    "original": "Distal phalanx of first finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofsecondfingerofhandl001": {
    "name": "Falange distal do 2º dedo da mão",
    "original": "Distal phalanx of second finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxofthirdfingerofhandl001": {
    "name": "Falange distal do 3º dedo da mão",
    "original": "Distal phalanx of third finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffourthfingerofhandl001": {
    "name": "Falange distal do 4º dedo da mão",
    "original": "Distal phalanx of fourth finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "distalphalanxoffifthfingerofhandl001": {
    "name": "Falange distal do 5º dedo da mão",
    "original": "Distal phalanx of fifth finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofsecondfingerofhandl001": {
    "name": "Falange média do 2º dedo da mão",
    "original": "Middle phalanx of second finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxofthirdfingerofhandl001": {
    "name": "Falange média do 3º dedo da mão",
    "original": "Middle phalanx of third finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffourthfingerofhandl001": {
    "name": "Falange média do 4º dedo da mão",
    "original": "Middle phalanx of fourth finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "middlephalanxoffifthfingerofhandl001": {
    "name": "Falange média do 5º dedo da mão",
    "original": "Middle phalanx of fifth finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffirstfingerofhandl001": {
    "name": "Falange proximal do 1º dedo da mão",
    "original": "Proximal phalanx of first finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofsecondfingerofhandl001": {
    "name": "Falange proximal do 2º dedo da mão",
    "original": "Proximal phalanx of second finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxofthirdfingerofhandl001": {
    "name": "Falange proximal do 3º dedo da mão",
    "original": "Proximal phalanx of third finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffourthfingerofhandl001": {
    "name": "Falange proximal do 4º dedo da mão",
    "original": "Proximal phalanx of fourth finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "proximalphalanxoffifthfingerofhandl001": {
    "name": "Falange proximal do 5º dedo da mão",
    "original": "Proximal phalanx of fifth finger of hand",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "firstmetacarpalbonel001": {
    "name": "1º metacarpal",
    "original": "First metacarpal bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "secondmetacarpalbonel001": {
    "name": "2º metacarpal",
    "original": "Second metacarpal bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "thirdmetacarpalbonel001": {
    "name": "3º metacarpal",
    "original": "Third metacarpal bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "fourthmetacarpalbonel001": {
    "name": "4º metacarpal",
    "original": "Fourth metacarpal bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "fifthmetacarpalbonel001": {
    "name": "5º metacarpal",
    "original": "Fifth metacarpal bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "capitatebonel001": {
    "name": "Osso capitato",
    "original": "Capitate bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "hamatebonel001": {
    "name": "Osso hamato",
    "original": "Hamate bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "lunatebonel001": {
    "name": "Osso semilunar",
    "original": "Lunate bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "pisiformbonel001": {
    "name": "Osso pisiforme",
    "original": "Pisiform bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "scaphoidbonel001": {
    "name": "Osso escafoide",
    "original": "Scaphoid bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "trapeziumbonel001": {
    "name": "Osso trapézio",
    "original": "Trapezium bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "trapezoidbonel001": {
    "name": "Osso trapezoide",
    "original": "Trapezoid bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "triquetrumbonel001": {
    "name": "Osso piramidal",
    "original": "Triquetrum bone",
    "side": "left",
    "region": "Mãos",
    "kind": "Estrutura óssea"
  },
  "scapulal001": {
    "name": "Escápula",
    "original": "Scapula",
    "side": "left",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "radiusl001": {
    "name": "Rádio",
    "original": "Radius",
    "side": "left",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "ulnal001": {
    "name": "Ulna",
    "original": "Ulna",
    "side": "left",
    "region": "Membros superiores",
    "kind": "Estrutura óssea"
  },
  "femurl001": {
    "name": "Fêmur",
    "original": "Femur",
    "side": "left",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "hipbonel001": {
    "name": "Osso do quadril",
    "original": "Hip bone",
    "side": "left",
    "region": "Pelve",
    "kind": "Estrutura óssea"
  },
  "tibial001": {
    "name": "Tíbia",
    "original": "Tibia",
    "side": "left",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "fibulal001": {
    "name": "Fíbula",
    "original": "Fibula",
    "side": "left",
    "region": "Membros inferiores",
    "kind": "Estrutura óssea"
  },
  "posteriorcellsofethmoidbonel001": {
    "name": "Células etmoidais posteriores",
    "original": "Posterior cells of ethmoid bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "middlecellsofethmoidbonel001": {
    "name": "Células etmoidais médias",
    "original": "Middle cells of ethmoid bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "anteriorcellsofethmoidbonel001": {
    "name": "Células etmoidais anteriores",
    "original": "Anterior cells of ethmoid bone",
    "side": "left",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "posteriorcellsofethmoidboner001": {
    "name": "Células etmoidais posteriores",
    "original": "Posterior cells of ethmoid bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "middlecellsofethmoidboner001": {
    "name": "Células etmoidais médias",
    "original": "Middle cells of ethmoid bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "anteriorcellsofethmoidboner001": {
    "name": "Células etmoidais anteriores",
    "original": "Anterior cells of ethmoid bone",
    "side": "right",
    "region": "Cabeça e pescoço",
    "kind": "Cavidade"
  },
  "eighthribl001": {
    "name": "8ª costela",
    "original": "Eighth rib",
    "side": "left",
    "region": "Tórax",
    "kind": "Estrutura óssea"
  }
};
